### ISSUE TITLE
[New Handler] Youtube View History

### ISSUE THREAD

**Issue by tahpot** [verida/data-connector-server#145]
Track what videos a user has watched.

**Comment by chime3** [comment]
### Video Watch History
Youtube API doesn't support watch history since 2015 to protect user privacy.
The only way to access watch history is to  manually download activity data using [Google Takeout](https://takeout.google.com/).

### Music Listen History
Technically, music upload counts as a `video` as well, which may include static images or lyrics.
Although tracking listening history through Youtube Data API v3 isn't possible, `Playlists` API is the most appropriate method to achieve this.

Youtube has two default playlists tied to each user's account: 
-  **Watch Later**: saved videos to watch later
- **Liked Videos**: all videos the user has liked (`youtube-favorite` WE DID)

Also, users can create personal playlists as many as possible to save videos.

`playlists.list` and `playlistItems.list` endpoints are available to retrieve playlists and the videos within playlists.(TESTED)

### Google Portability API

The **Google Portability API** allows users to download their data from various Google services, but it does not directly provide an API endpoint to retrieve YouTube watch history programmatically.

**Notes:** 
Portability APIs often have restrictions regarding access to sensitive data due to privacy.

**Comment by tahpot** [comment]
> The **Google Portability API** allows users to download their data from various Google services, but it does not directly provide an API endpoint to retrieve YouTube watch history programmatically.

@chime3  Just to confirm, the Youtube watch history **is** included in the **Google Portability API**?

**Comment by chime3** [comment]
> > The **Google Portability API** allows users to download their data from various Google services, but it does not directly provide an API endpoint to retrieve YouTube watch history programmatically.
> 
> [@chime3](https://github.com/chime3) Just to confirm, the Youtube watch history **is** included in the **Google Portability API**?

Yeah, it is included, but Google Portability API is designated for manual export rather than programmatical access.

**Comment by tahpot** [comment]
Noted. I will close this issue and we will cover Youtube watch history when we get to the #66
